package com.Banking_Somnath.banking_systemn.model;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
public class FixedDeposit {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY) // Link to the customer
    @JoinColumn(name = "customer_obj_mobile_number", referencedColumnName = "mobileNumber", nullable = false)
    private Customer customer; // Store the Customer object directly for easy access to customer details

    @Column(nullable = false)
    private String customerId; // Keep customerId as a direct string reference for simpler querying if needed

    @Column(nullable = false)
    private Double principalAmount;

    @Column(nullable = false)
    private Double interestRate; // Annual interest rate (percentage, e.g., 6.5 for 6.5%)

    @Column(nullable = false)
    private Integer termInMonths;

    private LocalDate startDate; // Date when the FD becomes active (set upon approval)

    private LocalDate maturityDate; // Calculated upon approval based on startDate and term

    private Double maturityAmount; // Calculated total amount customer will receive at maturity

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private FixedDepositStatus status;

    @Column(nullable = false)
    private LocalDateTime applicationDate; // When the customer submitted the request

    private LocalDateTime actionDate; // When admin approved/rejected it

    private String actionByAdminId; // Customer ID of the admin who took action

    @Column(length = 500) // Allow for a decent length rejection reason
    private String rejectionReason; // Reason if status is REJECTED

    @Column(nullable = false, length = 20) // Assuming account numbers are around this length
    private String sourceAccountNumber; // Customer's account from which principal was (or will be) debited

    // --- Constructors ---
    public FixedDeposit() {
        this.applicationDate = LocalDateTime.now();
        this.status = FixedDepositStatus.PENDING; // Default status on creation
    }

    // --- Getters and Setters ---
    // (Generated by IDE for all fields)

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public Double getPrincipalAmount() {
        return principalAmount;
    }

    public void setPrincipalAmount(Double principalAmount) {
        this.principalAmount = principalAmount;
    }

    public Double getInterestRate() {
        return interestRate;
    }

    public void setInterestRate(Double interestRate) {
        this.interestRate = interestRate;
    }

    public Integer getTermInMonths() {
        return termInMonths;
    }

    public void setTermInMonths(Integer termInMonths) {
        this.termInMonths = termInMonths;
    }

    public LocalDate getStartDate() {
        return startDate;
    }

    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    public LocalDate getMaturityDate() {
        return maturityDate;
    }

    public void setMaturityDate(LocalDate maturityDate) {
        this.maturityDate = maturityDate;
    }

    public Double getMaturityAmount() {
        return maturityAmount;
    }

    public void setMaturityAmount(Double maturityAmount) {
        this.maturityAmount = maturityAmount;
    }

    public FixedDepositStatus getStatus() {
        return status;
    }

    public void setStatus(FixedDepositStatus status) {
        this.status = status;
    }

    public LocalDateTime getApplicationDate() {
        return applicationDate;
    }

    public void setApplicationDate(LocalDateTime applicationDate) {
        this.applicationDate = applicationDate;
    }

    public LocalDateTime getActionDate() {
        return actionDate;
    }

    public void setActionDate(LocalDateTime actionDate) {
        this.actionDate = actionDate;
    }

    public String getActionByAdminId() {
        return actionByAdminId;
    }

    public void setActionByAdminId(String actionByAdminId) {
        this.actionByAdminId = actionByAdminId;
    }

    public String getRejectionReason() {
        return rejectionReason;
    }

    public void setRejectionReason(String rejectionReason) {
        this.rejectionReason = rejectionReason;
    }

    public String getSourceAccountNumber() {
        return sourceAccountNumber;
    }

    public void setSourceAccountNumber(String sourceAccountNumber) {
        this.sourceAccountNumber = sourceAccountNumber;
    }
}