package com.Banking_Somnath.banking_systemn.request;

// Assuming this is generic enough for Loans, FDs, Job Apps etc.
// Add validation later: @NotBlank
// import jakarta.validation.constraints.*;

public class RejectRequest {

    // @NotBlank(message = "Rejection reason cannot be blank")
    private String reason;

    // Getters and Setters (Generated by IDE)
    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }
}